apiVersion: v1
kind: Pod
metadata:
  labels:
    run: leaf
  name: leaf-2
spec:
  containers:
  - image: nginx
    name: leaf
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
